#! /bin/sh

# This file is part of Zed Tool, see <https://qu1x.org/z2l>.
# 
# Copyright (c) 2016 Rouven Spreckels <n3vu0r@qu1x.org>
# 
# Zed Tool is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation on 19 November 2007.
# 
# Zed Tool is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with Zed Tool. If not, see <https://www.gnu.org/licenses>.

# SoC temperature in millidegree Celsius

adc=$(echo /sys/devices/soc0/amba/*.adc/iio:device0 | awk '{ print $1 }')

raw=$(cat $adc/in_temp0_raw)
offset=$(cat $adc/in_temp0_offset)
scale=$(cat $adc/in_temp0_scale)

calc() { awk 'BEGIN { OFMT="%."'"$2"'"f"; print '"$1"'; exit}'; }

calc "($raw+$offset)*$scale" 0
